openapi: 3.0.0
info:
  description: WASAPhoto app backend REST APIs
  title: WASAPhoto
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: "User"
    description: User operations
  - name: "Photo"
    description: Photo operations
  - name: "login"
    description: Operations for login
components:
  responses:
    Unauthorized:
      description: The client could not authenticate a request.
    BadRequest:
      description: The request was not compliant with the documentation (eg.missing fields, etc).
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs.
  parameters:
    photoId:
      schema:
        type: integer
        example: 001
        minimum: 0
        readOnly: true
      name: photoId
      in: path
      required: true
      description: The unique photo identifier
    userId:
      schema:
        type: integer
        example: 32
        minimum: 0
        readOnly: true
      name: userId
      in: path
      required: true
      description: The unique user identifier
    username:
      name: username
      required: true
      description: The username of the user posted the photo
      in: path
      schema:
        type: string
        example: "Alice"
        pattern: "ˆ.*?$"
        minLength: 3
        maxLength: 20
    Sort:
      schema:
        type: string
        pattern: "ˆ.*?$"
        enum: ["date", "asc", "desc"]
        example: date
        minLength: 3
        maxLength: 15
      name: sort
      description: The way to sort the results
      in: query
      required: false
  schemas:
    DateTime:
      description: The date and time when the photo was uploaded
      type: string
      format: date
      example: 2022-01-01
    likes:
      description: The number of likes each photo has
      type: integer
      example: 32
      minimum: 0
    comments:
      description: The number of all comments of the user
      type: integer
      example: 12
      minimum: 0
    path:
      description: The url path of the photo
      type: string
      pattern: "ˆ.*?$"
      minLength: 1
      maxLength: 200
    photo:
      title: Photo
      description: This object represents a single photo
      type: object
      properties:
        id:
          $ref: "#/components/parameters/photoId"
        username:
          $ref: "#/components/parameters/username"
        userId:
          $ref: "#/components/parameters/userId"
        DateTime:
          $ref: "#/components/schemas/DateTime"
        likes:
          $ref: "#/components/schemas/likes"
        comments:
          $ref: "#/components/schemas/comments"
        path:
          $ref: "#/components/schemas/path"
    user:
      title: User
      description: This object represents a user
      type: object
      properties:
        id:
          $ref: "#/components/parameters/userId"
        username:
          $ref: "#/components/parameters/username"
        photosCount:
          description: The total number of uploaded photos by this user
          type: integer
          example: 87
          minimum: 0
        followers:
          description: List of usernames of user's followers.
          type: object
          minItems: 0
        followersCount:
          description: The total number of users that follow the current user
          example: 24
          type: integer
          minimum: 0
        followings:
          description: List of usernames of users that the current user is following.
          type: object
          minItems: 0
        followingsCount:
          description: The total number of users that are followed by current user
          example: 52
          type: integer
          minimum: 0
        photosPath:
          description: List of paths of photos that the user uploaded.
          type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /users/:
    parameters:
      - $ref: "#/components/parameters/Sort"
    get:
      tags: ["User"]
      operationId: listUsers
      summary: List all the users
      description: Returns the list of users
      responses:
        200:
          description: User/s found
          content:
            application/json:
              schema:
                description: The list of all the users
                type: array
                items: { $ref: "#/components/schemas/user" }
                minItems: 0
                maxItems: 1000
        401: { $ref: "#/components/responses/Unauthorized" }
        400: { $ref: "#/components/responses/BadRequest" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /users/{userId}/:
    parameters:
      - $ref: "#/components/parameters/userId"
    put:
      tags: ["User"]
      operationId: setMyUserName
      summary: Update username
      description: The username of the user is updated with the specified one
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        200:
          description: The user's username was updated
          content:
            application/json:
              schema: { $ref: "#/components/schemas/user" }
        400: { $ref: "#/components/responses/BadRequest" }
        404:
          description: User not found
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []
  /users/{userId}/profile/{username}/:
    get:
      tags: ["User"]
      operationId: getUserProfile
      summary: Get a specific user by ID
      description: Returns the user
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/username"
      responses:
        200:
          description: The user is returned
          content:
            application/json:
              schema: { $ref: "#/components/schemas/user" }
        400: { $ref: "#/components/responses/BadRequest" }
        404:
          description: User not found
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []
  /users/{userId}/followings/:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/Sort"
    get:
      tags: ["User"]
      summary: All the users that the current user is following
      description: Returns all users that the authenticated user is following.
      operationId: getFollowings
      responses:
        200:
          description: The followed users were returned.
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/user" }
                minItems: 0
                maxItems: 1000
        400: { $ref: "#/components/responses/BadRequest" }
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []

  /users/{userId}/followings/{followedUserId}/:
    parameters:
      - $ref: "#/components/parameters/userId"
      - name: followedUserId
        description: The id of the user to unfollow.
        in: path
        required: true
        schema:
          type: integer
          example: 2
    delete:
      tags: ["User"]
      operationId: unfollowUser
      summary: Unfollow a user
      description: The current user stops following another user."
      responses:
        204: { description: "The user was unfollowed." }
        400: { $ref: "#/components/responses/BadRequest" }
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []
    put:
      tags: ["User"]
      operationId: followUser
      summary: Follow a specific user
      description: The current user becomes a follower of another user.
      responses:
        204:
          description: The user started following the other user.
        400: { $ref: "#/components/responses/BadRequest" }
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []
  /users/{userId}/stream/:
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      tags: ["Photo"]
      operationId: getMyStream
      summary: Get a list of all the photos of a user's followings
      description: Returns a list of all the photos of a user's followings in reverse chronological order
      responses:
        200:
          description: The photos are returned
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/photo" }
                minItems: 0
                maxItems: 1000
        400: { $ref: "#/components/responses/BadRequest" }
        500: { $ref: "#/components/responses/InternalServerError" }
        401: { $ref: "#/components/responses/Unauthorized" }
      security:
        - bearerAuth: []
  /users/{userId}/photos/:
    parameters:
      - $ref: "#/components/parameters/userId"
    post:
      tags: ["Photo"]
      operationId: uploadPhoto
      summary: Upload a photo
      description: Uploads a new photo in the user's account
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/photo" }
      responses:
        201:
          description: Photo uploaded successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/photo" }
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /users/{userId}/banned/{bannedUserId}/:
    parameters:
      - $ref: "#/components/parameters/userId"
      - name: bannedUserId
        description: The id of the user to unban.
        in: path
        required: true
        schema:
          type: integer
          example: 2
    delete:
      tags: ["User"]
      operationId: unbanUser
      summary: Unban a user
      description: The current user unbans another user."
      responses:
        204: { description: The user was unbanned. }
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
    put:
      tags: ["User"]
      operationId: banUser
      summary: Ban a specific user
      description: The current user bans another user.
      responses:
        204:
          description: The user was banned.
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /photos/{photoId}/likes/{userId}/:
    parameters:
      - $ref: "#/components/parameters/photoId"
      - $ref: "#/components/parameters/userId"
    get:
      tags: ["Photo"]
      summary: Get all the likes of the photo
      description: Returns the id of the user, the id of the like and the id of the current photo.
      operationId: GetAllLikesPhoto
      responses:
        200:
          description: "The likes were returned."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
                  minItems: 0
                  maxItems: 1000
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
    put:
      tags: ["Photo"]
      summary: A user likes a photo
      description: A specific user likes a photo, creating a new like
      operationId: likePhoto
      responses:
        204:
          description: The photo was liked.
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
    delete:
      tags: ["Photo"]
      summary: A user unlikes a photo
      description: The specified user unlikes a photo that they previously liked.'
      operationId: unlikePhoto
      responses:
        204:
          description: The photo was unliked.
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []

  /photos/{photoId}/:
    parameters:
      - $ref: "#/components/parameters/photoId"
    delete:
      tags: ["Photo"]
      operationId: deletePhoto
      summary: Remove a Photo
      description: Remove a photo from the system.
      responses:
        204: { description: Photo deleted successfully }
        400: { $ref: "#/components/responses/BadRequest" }
        404: { description: Photo not found }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /photos/{photoId}/comments/:
    parameters:
      - $ref: "#/components/parameters/photoId"
      - $ref: "#/components/parameters/Sort"
    get:
      tags: ["Photo"]
      operationId: getComments
      summary: Get all the comments on a Photo
      description: Returns all the comments on a specified photo
      responses:
        200:
          description: "All the comments of a photo are returned."
          content:
            application/json:
              schema:
                type: array
                items: { $ref: "#/components/schemas/comments" }
                minItems: 0
                maxItems: 200
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []

    post:
      tags: ["Photo"]
      operationId: commentPhoto
      summary: Add a comment to a photo
      description: Adds a new comment to a specific photo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  description: The content of the comment
                  example: Such a cool photo! :)
                  type: string
                  pattern: "ˆ.*?$"
                  minLength: 1
                  maxLength: 200
      responses:
        201:
          description: "The comment was added."
          content:
            application/json:
              schema: { $ref: "#/components/schemas/comments" }
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /photos/{photoId}/comments/{commentId}/:
    parameters:
      - $ref: "#/components/parameters/photoId"
    delete:
      tags: ["Photo"]
      operationId: uncommentPhoto
      summary: Delete a comment of a video
      description: Deletes a comment of a video if and only if the user is the autor of the comment
      parameters:
        - name: commentId
          description: The id of the comment
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        204: { description: Comment deleted successfully }
        400: { $ref: "#/components/responses/BadRequest" }
        401: { $ref: "#/components/responses/Unauthorized" }
        404: { description: comment not found }
        500: { $ref: "#/components/responses/InternalServerError" }
      security:
        - bearerAuth: []
  /session/:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |
        If the user does not exist, it will be created, and an identifier is returned. If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: "ˆ.*?$"
                  minLength: 3
                  maxLength: 20
        required: true
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
